apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: performance
  namespace: openshift-operators
spec:
  cpu:
    isolated: 2-5
    reserved: 0-1
  hugepages:
    defaultHugepagesSize: 1G
    pages:
    - size: 1G
      count: 10
  realTimeKernel:
    enabled: true
  nodeSelector:
          node-role.kubernetes.io/worker-epa: ""
  machineConfigPoolSelector:
    machineconfiguration.openshift.io/role: worker-epa
